version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    container_name: gitlab
    command:
    - --loglevel warning
    volumes:
    - /var/aplicaciones/docker/gitlab/data/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.5-1
    container_name: gitlab
    volumes:
    - /var/aplicaciones/docker/gitlab/data/postgresql:/var/lib/postgresql:Z
    env_file: environment.env

  gitlab:
    restart: always
    image: unludgs/gitlab:latest
    container_name: gitlab
    depends_on:
    - redis
    - postgresql
    ports:
    - "10443:443"
    - "10022:22"
    volumes:
    - /var/aplicaciones/docker/gitlab/data/gitlab:/home/git/data:Z
    env_file: environment.env
    
