postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-20
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - /var/lib/postgresql
gitlab:
  restart: always
  image: sameersbn/gitlab:unlu
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=false
    - TZ=America/Argentina
    - GITLAB_TIMEZONE=America/Argentina/Buenos_Aires

    - GITLAB_SECRETS_DB_KEY_BASE=PFKbkjnNg3nHsVNphkqHCbW3XTcLzpfJvqN9rcn9zPs4WNFxbmxbLdnzfHK9tzTb

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notificaciones@unlu.edu.ar
    - GITLAB_EMAIL_REPLY_TO=noreply@unlu.edu.ar
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@unlu.edu.ar

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=www.unlu.edu.ar
    - SMTP_HOST=mail.unlu.edu.ar
    - SMTP_PORT=25
    - SMTP_USER=gitlab@unlu.edu.ar
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
    - TERM=xterm
    - http_proxy=http://proxy.unlu.edu.ar:8080
  volumes:
    - /home/git/data
redis:
  restart: always
  image: sameersbn/redis:latest
  volumes:
    - /var/lib/redis
